AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'config/initializers/simple_form.rb'
   - 'config/initializers/simple_form_bootstrap.rb'
   - 'client/node_modules/**/*'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignArray:
  Enabled: false
